export const config ={
    HOST: "daricapp://autoquit",
    PORT: 7709,
    DEFAULT_PROCESS_ICON: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACMAAAAbCAIAAAB5kqHOAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAEZSURBVEhL7dTNCoJAFAVgIYKIIILoWYt+KKpF0DoQepqIXqH0AXoA/2tjN+91atSujE2uOhzcNR9nMI24rtQurTdb7cWTRbRJh+Mp88STRV7SVWs46f51bmmiKFLYBL80hme+CGAISZhyaWfusUIarOz+0u4t7O7c6sys9tRqTS7N8aUxIsksShiGypsYRmyiLekaYKpIDIMSrZBTLuVvj2GgtEVeAwmCQHkTw0DBoBVyqkgMAy1cgymR8rfHMFAwaIUc3/eVNzEMtHANMFUkhoECQCvklEv52+NbuAbieZ7yJr6ZTYLRL9EWeQ3mJxIhb4zrumoSJPkCPJP8bT6+aRBCEkZZIkSdcRyHk7QXTxYhqYb8peqJ4wdV7/x/s7or5wAAAABJRU5ErkJggg==',
    get URL() { return `${config.HOST}:${config.PORT}`; }
}